"""Generate config/smoke_ids.txt: a frozen, stratified-by-question_type
50-question subset selected with seed=42 from longmemeval_s_cleaned.json.

After running this once you MUST commit the resulting file. The harness
reads from it directly so reviewers reproducing `make reproduce` (smoke
mode) get the identical 50 questions.
"""

from __future__ import annotations

import json
import random
import sys
from collections import defaultdict
from pathlib import Path


N_TOTAL = 50
SEED = 42
SRC = Path("data/longmemeval_s_cleaned.json")
DST = Path("config/smoke_ids.txt")


def main() -> int:
    if not SRC.exists():
        print(f"error: {SRC} missing. Run `make data` first.", file=sys.stderr)
        return 2

    data = json.loads(SRC.read_text())

    # Group by question_type (keeping _abs grouped with its base type per upstream).
    by_type: dict[str, list[str]] = defaultdict(list)
    for entry in data:
        qtype = entry["question_type"]
        by_type[qtype].append(entry["question_id"])

    types = sorted(by_type.keys())
    rng = random.Random(SEED)

    # Largest-remainder allocation across types so the counts sum to N_TOTAL.
    raw = {t: N_TOTAL * len(by_type[t]) / sum(len(v) for v in by_type.values()) for t in types}
    floor = {t: int(raw[t]) for t in types}
    remainder = N_TOTAL - sum(floor.values())
    # Distribute the remainder by fractional part (desc), tie-break alphabetical.
    order = sorted(types, key=lambda t: (-(raw[t] - floor[t]), t))
    quota = dict(floor)
    for t in order[:remainder]:
        quota[t] += 1

    selected: list[str] = []
    for t in types:
        pool = sorted(by_type[t])  # deterministic order before shuffling
        rng.shuffle(pool)
        selected.extend(pool[: quota[t]])

    selected.sort()
    header = [
        "# Frozen stratified 50-question smoke subset for `make reproduce` smoke mode.",
        f"# Source: {SRC} (sha256 pinned via data/CHECKSUMS.sha256)",
        f"# Generated by scripts/build_smoke_ids.py at seed={SEED}, N={N_TOTAL}.",
        "# DO NOT hand-edit; regenerate from the script if the dataset changes.",
    ]
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(header + selected) + "\n")

    print(f"wrote {DST} with {len(selected)} question_ids")
    by_picked: dict[str, int] = defaultdict(int)
    qid2type = {e["question_id"]: e["question_type"] for e in data}
    for q in selected:
        by_picked[qid2type[q]] += 1
    for t in sorted(by_picked):
        print(f"  {t}: {by_picked[t]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
